[build]
  publish = "dist/"
  command = "yarn build"

[build.environment]
  NETLIFY_USE_YARN = "true"

[[redirects]]
  from    = "/fireflies"
  to      = "/index.html"
  status  = 200

[[redirects]]
  from    = "/"
  to      = "https://jerem.xyz/fireflies"
  status  = 200
  force   = true