export const NAV = '.nav'
export const NAV_TITLE = '.nav__title'
export const NAV_LINK = '.nav__link'
export const NAV_DECORATION = '.nav__decoration'

export const FORM = '.form'
export const FORM_INPUT_WRAPPER = '.form__input-wrapper'
export const FORM_INPUT = '.form__input'
export const FORM_INPUT_BORDER = '.form__input-border'
export const FORM_INSTRUCTIONS = '.form__instructions'
export const FORM_INSTRUCTIONS_TEXT = '.form__instructions-text'
export const FORM_INSTRUCTIONS_DECORATION = '.form__instructions-decoration'
export const FORM_ENTER_KEY = '.form__enter-key'
export const FORM_ENTER_KEY_DESC = '.form__enter-key-desc'

export const ASIDE = '.aside'
export const STAGE = '.stage'

export const EASE_EXPO = 'expo'
export const ENTER_KEY = 'Enter'
